import jsPDF from "jspdf";

export default function generateLivePDF({
  primary_disease,
  severity,
  infection_ratio,
  avg_confidence,
  recommendation,
}) {
  const doc = new jsPDF();
  let y = 20;

  /* ================= HEADER ================= */
  doc.setFillColor(34, 139, 34);
  doc.rect(0, 0, 210, 25, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.text("Plant Disease Live Detection Report", 105, 16, {
    align: "center",
  });

  doc.setFontSize(10);
  doc.text("Offline AI-based Drone / Camera Analysis", 105, 22, {
    align: "center",
  });

  doc.setTextColor(0, 0, 0);
  y = 40;

  /* ================= SUMMARY ================= */
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.text("Disease Summary (Live Analysis)", 10, y);
  y += 10;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);

  doc.text(
    `Detected Disease: ${primary_disease || "Healthy Crop"}`,
    10,
    y
  );
  y += 7;

  doc.text(`Severity Level: ${severity}`, 10, y);
  y += 7;

  doc.text(`Infected Duration: ${infection_ratio}%`, 10, y);
  y += 7;

  doc.text(`Detection Confidence: ${avg_confidence}%`, 10, y);

  y += 15;

  /* ================= RECOMMENDATION ================= */
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.text("Recommended Action", 10, y);
  y += 8;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);

  // HEALTHY
  if (recommendation?.type === "healthy") {
    const msg =
      "No disease detected during live monitoring.\n" +
      "No pesticide required.\n" +
      "Continue standard crop management practices.";

    const lines = doc.splitTextToSize(msg, 180);
    doc.text(lines, 10, y);
    y += lines.length * 6;
  }

  // VIRAL
  else if (recommendation?.type === "viral") {
    const msg =
      "⚠ Viral Disease Detected\n" +
      "• Chemical pesticides are ineffective\n" +
      "• Remove infected plants immediately\n" +
      "• Control insect vectors\n" +
      "• Maintain field hygiene";

    const lines = doc.splitTextToSize(msg, 180);
    doc.text(lines, 10, y);
    y += lines.length * 6;
  }

  // CHEMICAL
  else if (recommendation?.pesticide) {
    doc.text("Chemical Control Recommended", 10, y);
    y += 7;

    doc.text(`Pesticide: ${recommendation.pesticide}`, 10, y);
    y += 7;

    doc.text(`Dosage: ${recommendation.dose}`, 10, y);
    y += 7;

    doc.text(`Spray Interval: ${recommendation.interval}`, 10, y);
    y += 7;

    if (recommendation.max_sprays) {
      doc.text(`Max Sprays: ${recommendation.max_sprays}`, 10, y);
      y += 7;
    }
  }

  /* ================= FOOTER ================= */
  doc.setFontSize(9);
  doc.setTextColor(80);

  doc.text(
    "Disclaimer: This AI-generated report is for advisory purposes only.",
    10,
    280
  );
  doc.text(
    "Consult local agriculture officers before pesticide application.",
    10,
    286
  );
  doc.text(
    "Generated by Plant Leaf Disease AI System (Offline Mode)",
    10,
    292
  );

  doc.save("Live_Plant_Disease_Report.pdf");
}
