import jsPDF from "jspdf";

export default function generateVideoResultPDF({
  disease = "Healthy Crop",
  severity = "NONE",
  infected_leaf_percent = 0,
  recommendation = {},
  landArea = "",
  quantity = null,
}) {
  const doc = new jsPDF();
  let y = 20;

  // ===============================
  // HEADER
  // ===============================
  doc.setFillColor(34, 139, 34);
  doc.rect(0, 0, 210, 25, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.text("Plant Disease Video Advisory Report", 105, 16, {
    align: "center",
  });

  doc.setFontSize(10);
  doc.text("AI-based Guidance for Farmers", 105, 22, {
    align: "center",
  });

  doc.setTextColor(0, 0, 0);
  y = 35;

  // ===============================
  // DISEASE SUMMARY
  // ===============================
  doc.setFillColor(240, 248, 240);
  doc.rect(10, y - 6, 190, 40, "F");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.text("Disease Summary (Video Analysis)", 12, y);
  y += 8;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);

  doc.text(`Detected Disease: ${disease}`, 12, y); y += 7;
  doc.text(`Severity Level: ${severity}`, 12, y); y += 7;
  doc.text(`Infected Leaf Area: ${infected_leaf_percent}%`, 12, y);

  y += 15;

  // ===============================
  // RECOMMENDED ACTION
  // ===============================
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.text("Recommended Action", 10, y);
  y += 6;

  // -------------------------------
  // VIRAL CASE
  // -------------------------------
  if (recommendation?.type === "viral") {
    doc.setFillColor(255, 235, 235);
    doc.rect(10, y - 4, 190, 50, "F");

    doc.setTextColor(180, 0, 0);
    doc.setFontSize(12);
    doc.text("⚠ Viral Disease Detected", 12, y);
    y += 8;

    doc.setTextColor(0, 0, 0);
    doc.setFontSize(11);

    const viralText =
      "• Chemical pesticides are NOT effective\n" +
      "• Remove infected plants immediately\n" +
      "• Control insect vectors (whitefly, aphids)\n" +
      "• Maintain field hygiene";

    const lines = doc.splitTextToSize(viralText, 180);
    doc.text(lines, 12, y);
    y += lines.length * 6 + 8;
  }

  // -------------------------------
  // CHEMICAL (FUNGAL / BACTERIAL)
  // -------------------------------
  else if (recommendation?.pesticide) {
    doc.setFillColor(235, 245, 255);
    doc.rect(10, y - 4, 190, 60, "F");

    doc.setTextColor(0, 70, 140);
    doc.setFontSize(12);
    doc.text("Chemical Control Recommended", 12, y);
    y += 10;

    doc.setTextColor(0, 0, 0);
    doc.setFontSize(11);

    doc.text(`Pesticide: ${recommendation.pesticide}`, 12, y); y += 7;
    doc.text(`Dosage: ${recommendation.dose}`, 12, y); y += 7;
    doc.text(`Spray Interval: ${recommendation.interval}`, 12, y); y += 7;
    doc.text(`Max Sprays: ${recommendation.max_sprays}`, 12, y); y += 7;

    // ✅ LAND AREA CALCULATION (FIXED)
    if (landArea !== "" && quantity) {
      doc.text(`Farmer Land Area: ${landArea} hectare(s)`, 12, y); 
      y += 7;

      doc.text(
        `Total Pesticide Required: ${quantity.grams.toFixed(2)} grams`,
        12,
        y
      );
      y += 7;
    }

    y += 6;
  }

  
  // -------------------------------
  // HEALTHY CASE
  // -------------------------------
  else {
    doc.setFillColor(245, 245, 245);
    doc.rect(10, y - 4, 190, 30, "F");

    doc.setFontSize(11);
    const msg =
      "No disease detected in the video.\n" +
      "No chemical pesticide required.\n" +
      "Follow standard crop management practices.";

    const lines = doc.splitTextToSize(msg, 180);
    doc.text(lines, 12, y);
    y += lines.length * 6 + 8;
  }

  // ===============================
  // FOOTER
  // ===============================
  doc.setDrawColor(180);
  doc.line(10, 275, 200, 275);

  doc.setFontSize(9);
  doc.setTextColor(80);
  doc.text(
    "Disclaimer: This AI-generated report is for advisory purposes only.",
    10,
    282
  );
  doc.text(
    "Please consult local agriculture officers before applying pesticides.",
    10,
    288
  );
  doc.text(
    "Generated by Plant Leaf Disease AI System",
    10,
    294
  );

  doc.save("Plant_Disease_Video_Report.pdf");
}
